apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: ensarhamzic/bs-api-gateway:latest
          ports:
            - containerPort: 8080
          env:
            - name: Urls__UsersManagement
              value: "http://user-management-service:8080/api"
            - name: Urls__RoutesManagement
              value: "http://route-management-service:8080/api"
            - name: Urls__TicketsManagement
              value: "http://ticket-management-service:8080/api"
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "0.5"
              memory: "500Mi"
      initContainers:
        - name: check-user-management-service
          image: busybox:1.36.1
          command: ['sh', '-c', 'until wget -qO- http://user-management-service:8080/healthz; do echo waiting for user-management-service; sleep 2; done;']
        - name: check-route-management-service
          image: busybox:1.36.1
          command: ['sh', '-c', 'until wget -qO- http://route-management-service:8080/healthz; do echo waiting for route-management-service; sleep 2; done;']
        - name: check-ticket-management-service
          image: busybox:1.36.1
          command: ['sh', '-c', 'until wget -qO- http://ticket-management-service:8080/healthz; do echo waiting for ticket-management-service; sleep 2; done;']