apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-management-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticket-management
  template:
    metadata:
      labels:
        app: ticket-management
    spec:
      containers:
        - name: ticket-management
          image: busstationgo:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: GIN_MODE
              value: "release"
            - name: MONGODB_CONNECTION_STRING
              value: "mongodb://mongodb-service:27017"
            - name: RABBITMQ_CONNECTION_STRING
              value: "amqp://admin:admin@rabbitmq-service:5672/"
      initContainers:
        - name: check-mongodb
          image: busybox:1.36.1
          command: ['sh', '-c', 'until nc -z -v -w30 mongodb-service 27017; do echo waiting for mongodb-service; sleep 2; done;']
        - name: check-rabbitmq
          image: busybox:1.36.1
          command: ['sh', '-c', 'until nc -z -v -w30 rabbitmq-service 5672; do echo waiting for rabbitmq-service; sleep 2; done;']
---
apiVersion: v1
kind: Service
metadata:
  name: ticket-management-service
spec:
  selector:
    app: ticket-management
  ports:
    - protocol: TCP
      port: 8080