apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  type: LoadBalancer
  selector:
    app: rabbitmq
  ports:
    - protocol: TCP
      name: rabbitmq
      port: 5672
      targetPort: 5672
    - protocol: TCP
      name: rabbitmq-management
      port: 15672
      targetPort: 15672